### ISSUE TITLE
Issues with certs / RSS feed

### ISSUE THREAD

**Issue by bmann** [CoSocial-Canada/notes#19]
> Having trouble with the RSS feed at https://cosocial.info/feed/ - my feed reader is reporting "unable to verify the first certificate", which suggests you need to add the intermediate certs. (It worked until a few days ago, so this seems to be a recent change, and I'm subscribed to other sites that use Let's Encrypt so it appears to be local to your site.)

See https://cosocial.ca/@me@mastodon.peterjanes.ca/110199107074645810

**Comment by evanp** [comment]
I tried to update the letsencrypt ca bundle in the Namecheap Blog hosting interface, but it wouldn't accept it.

I think the right solution is to move to another WordPress platform that's managed by tech-ops; see CoSocial-Canada/infra#23 .

For now, I'm going to buy one of Namecheap's low-cost SSL certs to use instead.

**Comment by evanp** [comment]
There has not been a recent change to the certs; I had to renew them a month or so ago.

**Comment by bmann** [comment]
This continues to be an issue, we’re going to move off NameCheap blog hosting.
