### ISSUE TITLE
Should we use a Github wiki for basic documentation for external users?

### ISSUE THREAD

**Issue by bmann** [CoSocial-Canada/notes#6]
Started this discussion @mszucs

**Comment by timbray** [comment]
My experience with Discourse has been perfectly OK, so I'd support that option since we have one person around who is confident about running it.

**Comment by bmann** [comment]
Thanks Tim.

@rorybray @walkah tagging you two in here as well. I'm putting a few things into the Github wiki but frankly it's annoying even for me.

I think `coop.cosocial.ca` as a Discourse forum, where we can have public / private info, mailing list-style communication, etc. is maybe the right call here.

I've kind of gone backwards in talking about this, there are a handful of different needs that I think are met by Discourse.

**Comment by walkah** [comment]
I'm certainly accustomed to Discourse. I guess my question is: how much do we want to self host here on a volunteer staff?

**Comment by bmann** [comment]
@walkah yes definitely a consideration. Need multiple people comfortable with anything we choose to self host. 

Feeling the need to get off our paid Slack instance (different thread but related in terms of what channels to use for what communications purpose) but also don’t _need_ a forum until we have more people. 

Obsidian + Git “works” but it means training our people internally which is a different kind of load. 

This thread starts with “should we use a GitHub wiki” and for me I think the answer is “nope” … but we can stash stuff there for now if needed ;)

**Comment by bmann** [comment]
I'm going to close this and put into the "Done" category. Github Wiki is a "nope", we need to discuss member communications vs staff operations.
